### ISSUE TITLE
Zengge Bluetooth RGB led strip not working in HA

### ISSUE THREAD

**Issue by kamm0r** [mjg59/python-zengge#4]
followed al the steps indicated but the integration Zengge generated this in the core (2022.5.3)

Logger: homeassistant.components.light
Source: components/zengge/light.py:66
Integration: Luce ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 00:35:02 (1 occurrences)
Last logged: 00:35:02
Error while setting up zengge platform for light

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/zengge/light.py", line 45, in setup_platform
light = ZenggeLight(device)
File "/usr/src/homeassistant/homeassistant/components/zengge/light.py", line 66, in init
if self._bulb.connect() is False:
File "/usr/local/lib/python3.9/site-packages/zengge/init.py", line 54, in connect
self.get_state()
File "/usr/local/lib/python3.9/site-packages/zengge/init.py", line 103, in get_state
self.send_packet(self.rgbwhandle, bytearray([0xef, 0x01, 0x77]))
AttributeError: 'zengge' object has no attribute 'rgbwhandle'

**Comment by abdel-elbel** [comment]
I believe this is due to a bug in https://github.com/mjg59/python-zengge, the python-zengge library doesn't check if the rgbwhandle class attribute is defined.
